### ISSUE TITLE
Generate forecasts for the future time stamps

### ISSUE THREAD

**Issue by Mo-Abdelhameed** [SalesforceAIResearch/uni2ts#2] opened 2024-03-21 19:36 UTC
I am trying to use the model on a pandas dataframe to generate forecast for future time stamps that the true values for are unknown. The provided examples focus on splitting a given dataframe into train/test and generate forecast for the test set. Can you please provide more examples on how to use it to generate forecast for new time stamps that are not present in the pandas dataframe?

Thanks for the great work!

**Comment by gorold** [comment] 2024-03-26 06:40
Hi @Mo-Abdelhameed thanks for using our model, and sorry for the delayed response. Here's an example on generating forecasts for a new time stamp:

```python
import torch
import pandas as pd
from gluonts.dataset.pandas import PandasDataset
from huggingface_hub import hf_hub_download

from uni2ts.model.moirai import MoiraiForecast


SIZE = "small"  # model size: choose from {'small', 'base', 'large'}
PDT = 20  # prediction length: any positive integer
CTX = 200  # context length: any positive integer
PSZ = "auto"  # patch size: choose from {"auto", 8, 16, 32, 64, 128}
BSZ = 32  # batch size: any positive integer
TEST = 100  # test set length: any positive integer

# Read data into pandas DataFrame
url = (
    "https://gist.githubusercontent.com/rsnirwan/c8c8654a98350fadd229b00167174ec4"
    "/raw/a42101c7786d4bc7695228a0f2c8cea41340e18f/ts_wide.csv"
)
df = pd.read_csv(url, index_col=0, parse_dates=True)

# Convert into GluonTS dataset
ds = PandasDataset(dict(df))

# Prepare pre-trained model by downloading model weights from huggingface hub
model = MoiraiForecast.load_from_checkpoint(
    checkpoint_path=hf_hub_download(
        repo_id=f"Salesforce/moirai-1.0-R-{SIZE}", filename="model.ckpt"
    ),
    prediction_length=PDT,
    context_length=CTX,
    patch_size=PSZ,
    num_samples=100,
    target_dim=1,
    feat_dynamic_real_dim=ds.num_feat_dynamic_real,
    past_feat_dynamic_real_dim=ds.num_past_feat_dynamic_real,
    map_location="cuda:0" if torch.cuda.is_available() else "cpu",
)

predictor = model.create_predictor(batch_size=BSZ)
forecasts = predictor.predict(ds)
forecast_it = iter(forecasts)
forecast = next(forecast_it)
forecast.plot()

```

**Comment by Mo-Abdelhameed** [comment] 2024-03-26 11:27
Thanks for the reply!

When I run the code as it is, I get the following error:

Exception ignored in: <generator object PyTorchPredictor.predict at 0x16f886ac0>
Traceback (most recent call last):
  File "/Users/moo/Desktop/ReadyTensor/Models/Forecasting/moirai/.venv/lib/python3.11/site-packages/gluonts/torch/model/predictor.py", line 89, in predict
  File "/Users/moo/Desktop/ReadyTensor/Models/Forecasting/moirai/.venv/lib/python3.11/site-packages/torch/autograd/grad_mode.py", line 84, in __exit__
TypeError: 'NoneType' object is not callable

do you have an idea on how to solve it?

**Comment by gorold** [comment] 2024-03-26 13:38
@Mo-Abdelhameed @jboornlp are you using windows?

**Comment by Mo-Abdelhameed** [comment] 2024-03-26 13:40
@gorold No, i'm on mac

**Comment by gorold** [comment] 2024-03-26 13:42
I can't reproduce this error. Could you run this line by line on a notebook and send a screenshot?

**Comment by gorold** [comment] 2024-03-26 13:42
Were you able to run the notebook examples previously?

**Comment by jboornlp** [comment] 2024-03-26 13:45
I'm on a Linux AMI - this is the first thing I'm trying to run - just a copy of the "getting started" code.  The environment seemed to install fine.

**Comment by Mo-Abdelhameed** [comment] 2024-03-26 13:51
Actually when I run the script in a notebook it runs fine 
<img width="1345" alt="Screenshot 2024-03-26 at 3 50 05 PM" src="https://github.com/SalesforceAIResearch/uni2ts/assets/73613367/41bebfa1-9a4d-4550-ae19-f008611d8b71">

I copied the whole script in one cell, but I still get the same error when running the same code in .py file

**Comment by gorold** [comment] 2024-03-26 14:45
Closing this issue since the original problem has been solved. See #3 for further discussion on the error.

**Closed by gorold** 2024-03-26 14:45 UTC

**Comment by Mo-Abdelhameed** [comment] 2024-03-26 14:51
@gorold  Thanks!
